version: '3.8'
services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python seed.py && python manage.py runserver 0.0.0.0:8000"
#    command: python main.py
    ports:
      - 0.0.0.0:8000:8000
